import type { CatalogItem } from "./types";

/**
 * Curated catalog. Dimensions are in feet and reflect typical real-world sizes.
 * `themes` is the set of styles a piece works well within — used for recommendations.
 */
export const CATALOG: CatalogItem[] = [
  // ----- seating -----
  {
    id: "sofa-3seat-72",
    name: "3-seat sofa (6')",
    category: "seating",
    shape: "rect",
    width: 6,
    depth: 2.83,
    themes: ["mid-century-modern", "scandi", "japandi", "minimalist", "modern-farmhouse"],
    color: "#8b6f47",
    recommendedClearance: 1.5,
    description: "Standard 3-seat sofa, ~72\" wide.",
  },
  {
    id: "sofa-3seat-84",
    name: "3-seat sofa (7')",
    category: "seating",
    shape: "rect",
    width: 7,
    depth: 3,
    themes: ["mid-century-modern", "industrial", "modern-farmhouse", "boho"],
    color: "#6b4f37",
    recommendedClearance: 1.5,
  },
  {
    id: "sofa-lshape-small",
    name: "L-shaped sofa (small)",
    category: "seating",
    shape: "l-shape",
    width: 7,
    depth: 5,
    lShape: { notchWidth: 4, notchDepth: 2.5 },
    themes: ["scandi", "modern-farmhouse", "minimalist", "industrial"],
    color: "#7a6147",
    recommendedClearance: 1.5,
    description: "Compact L-sectional, chaise on the right.",
  },
  {
    id: "sofa-lshape-large",
    name: "L-shaped sofa (large)",
    category: "seating",
    shape: "l-shape",
    width: 9,
    depth: 6.5,
    lShape: { notchWidth: 5, notchDepth: 3 },
    themes: ["modern-farmhouse", "industrial", "minimalist", "boho"],
    color: "#7a6147",
    recommendedClearance: 1.5,
  },
  {
    id: "loveseat",
    name: "Loveseat",
    category: "seating",
    shape: "rect",
    width: 5,
    depth: 2.75,
    themes: ["mid-century-modern", "scandi", "coastal", "art-deco"],
    color: "#9a7f5e",
    recommendedClearance: 1.5,
  },
  {
    id: "armchair",
    name: "Armchair",
    category: "seating",
    shape: "rect",
    width: 2.83,
    depth: 2.83,
    themes: ["mid-century-modern", "scandi", "japandi", "boho", "art-deco"],
    color: "#a48462",
    recommendedClearance: 1.5,
  },
  {
    id: "accent-chair-round",
    name: "Round accent chair",
    category: "seating",
    shape: "circle",
    width: 3,
    depth: 3,
    themes: ["mid-century-modern", "boho", "art-deco"],
    color: "#b89070",
    recommendedClearance: 1.5,
  },
  {
    id: "dining-chair",
    name: "Dining chair",
    category: "seating",
    shape: "rect",
    width: 1.5,
    depth: 1.5,
    themes: ["mid-century-modern", "scandi", "industrial", "japandi", "modern-farmhouse"],
    color: "#7c5a3a",
    recommendedClearance: 1,
  },
  {
    id: "barstool",
    name: "Barstool",
    category: "seating",
    shape: "circle",
    width: 1.25,
    depth: 1.25,
    themes: ["industrial", "scandi", "japandi", "modern-farmhouse"],
    color: "#3d2e22",
    recommendedClearance: 1,
  },

  // ----- tables -----
  {
    id: "coffee-table",
    name: "Coffee table",
    category: "tables",
    shape: "rect",
    width: 4,
    depth: 2,
    themes: ["mid-century-modern", "scandi", "industrial", "japandi", "modern-farmhouse"],
    color: "#5a4030",
    recommendedClearance: 1.2,
    description: "Place 12–18\" from sofa.",
  },
  {
    id: "coffee-table-round",
    name: "Coffee table (round)",
    category: "tables",
    shape: "circle",
    width: 3,
    depth: 3,
    themes: ["mid-century-modern", "boho", "japandi", "art-deco"],
    color: "#5a4030",
    recommendedClearance: 1.2,
  },
  {
    id: "side-table",
    name: "Side table",
    category: "tables",
    shape: "rect",
    width: 1.5,
    depth: 1.5,
    themes: ["mid-century-modern", "scandi", "industrial", "boho"],
    color: "#604535",
    recommendedClearance: 0.5,
  },
  {
    id: "dining-table-4",
    name: "Dining table — 4 person",
    category: "tables",
    shape: "rect",
    width: 4,
    depth: 2.83,
    themes: ["scandi", "modern-farmhouse", "minimalist", "japandi"],
    color: "#6b4a30",
    recommendedClearance: 3, // chairs + walk-by
    description: "Allow 3' clearance for chair pull-out + walking.",
  },
  {
    id: "dining-table-6",
    name: "Dining table — 6 person",
    category: "tables",
    shape: "rect",
    width: 6,
    depth: 3,
    themes: ["modern-farmhouse", "industrial", "mid-century-modern"],
    color: "#6b4a30",
    recommendedClearance: 3,
  },
  {
    id: "dining-table-round-4",
    name: "Round dining table",
    category: "tables",
    shape: "circle",
    width: 4,
    depth: 4,
    themes: ["scandi", "japandi", "coastal", "mid-century-modern"],
    color: "#6b4a30",
    recommendedClearance: 3,
  },
  {
    id: "desk",
    name: "Desk",
    category: "tables",
    shape: "rect",
    width: 5,
    depth: 2,
    themes: ["industrial", "minimalist", "scandi", "mid-century-modern"],
    color: "#4d3a2a",
    recommendedClearance: 3,
  },
  {
    id: "console-table",
    name: "Console table",
    category: "tables",
    shape: "rect",
    width: 5,
    depth: 1.25,
    themes: ["mid-century-modern", "art-deco", "coastal", "modern-farmhouse"],
    color: "#5a4030",
    recommendedClearance: 0.5,
  },

  // ----- beds -----
  {
    id: "bed-twin",
    name: "Twin bed",
    category: "beds",
    shape: "rect",
    width: 3.17, // 38"
    depth: 6.25, // 75"
    themes: ["scandi", "minimalist", "japandi", "modern-farmhouse"],
    color: "#9a7f5e",
    recommendedClearance: 2,
  },
  {
    id: "bed-full",
    name: "Full bed",
    category: "beds",
    shape: "rect",
    width: 4.5, // 54"
    depth: 6.25,
    themes: ["scandi", "minimalist", "japandi", "modern-farmhouse"],
    color: "#9a7f5e",
    recommendedClearance: 2,
  },
  {
    id: "bed-queen",
    name: "Queen bed",
    category: "beds",
    shape: "rect",
    width: 5, // 60"
    depth: 6.67, // 80"
    themes: ["mid-century-modern", "scandi", "japandi", "modern-farmhouse", "minimalist"],
    color: "#9a7f5e",
    recommendedClearance: 2.5,
    description: "Leave at least 2' on each side for walking + dressing.",
  },
  {
    id: "bed-king",
    name: "King bed",
    category: "beds",
    shape: "rect",
    width: 6.33, // 76"
    depth: 6.67,
    themes: ["modern-farmhouse", "industrial", "art-deco", "minimalist"],
    color: "#9a7f5e",
    recommendedClearance: 2.5,
  },
  {
    id: "nightstand",
    name: "Nightstand",
    category: "storage",
    shape: "rect",
    width: 1.83,
    depth: 1.5,
    themes: ["mid-century-modern", "scandi", "industrial", "japandi", "modern-farmhouse", "art-deco"],
    color: "#5a4030",
    recommendedClearance: 0.5,
  },

  // ----- storage -----
  {
    id: "dresser",
    name: "Dresser",
    category: "storage",
    shape: "rect",
    width: 5,
    depth: 1.67,
    themes: ["mid-century-modern", "scandi", "modern-farmhouse", "industrial"],
    color: "#4d3a2a",
    recommendedClearance: 2.5, // pull drawers
  },
  {
    id: "tallboy",
    name: "Tallboy dresser",
    category: "storage",
    shape: "rect",
    width: 3,
    depth: 1.5,
    themes: ["scandi", "japandi", "minimalist", "modern-farmhouse"],
    color: "#5a4030",
    recommendedClearance: 2.5,
  },
  {
    id: "bookshelf",
    name: "Bookshelf",
    category: "storage",
    shape: "rect",
    width: 3,
    depth: 1,
    themes: ["industrial", "mid-century-modern", "boho", "scandi"],
    color: "#3d2e22",
    recommendedClearance: 1.5,
  },
  {
    id: "tv-stand",
    name: "TV stand / media console",
    category: "storage",
    shape: "rect",
    width: 5,
    depth: 1.33,
    themes: ["mid-century-modern", "scandi", "industrial", "minimalist"],
    color: "#3d2e22",
    recommendedClearance: 1,
  },

  // ----- rugs -----
  {
    id: "rug-5x7",
    name: "Rug 5' × 7'",
    category: "rugs",
    shape: "rect",
    width: 5,
    depth: 7,
    themes: ["scandi", "japandi", "minimalist", "coastal"],
    color: "#d6c9b0",
    recommendedClearance: 0,
    description: "Best for small seating areas.",
  },
  {
    id: "rug-8x10",
    name: "Rug 8' × 10'",
    category: "rugs",
    shape: "rect",
    width: 8,
    depth: 10,
    themes: ["mid-century-modern", "scandi", "boho", "modern-farmhouse"],
    color: "#c9b896",
    recommendedClearance: 0,
    description: "Common living room size — front legs of sofa should sit on it.",
  },
  {
    id: "rug-9x12",
    name: "Rug 9' × 12'",
    category: "rugs",
    shape: "rect",
    width: 9,
    depth: 12,
    themes: ["modern-farmhouse", "boho", "industrial", "art-deco"],
    color: "#bba883",
    recommendedClearance: 0,
  },
  {
    id: "rug-round-6",
    name: "Round rug (6')",
    category: "rugs",
    shape: "circle",
    width: 6,
    depth: 6,
    themes: ["boho", "japandi", "scandi", "art-deco"],
    color: "#d6c9b0",
    recommendedClearance: 0,
  },

  // ----- lighting -----
  {
    id: "floor-lamp",
    name: "Floor lamp",
    category: "lighting",
    shape: "circle",
    width: 1.5,
    depth: 1.5,
    themes: ["mid-century-modern", "scandi", "industrial", "art-deco", "japandi"],
    color: "#222",
    recommendedClearance: 0.5,
  },

  // ----- misc -----
  {
    id: "plant-large",
    name: "Large planter",
    category: "misc",
    shape: "circle",
    width: 2,
    depth: 2,
    themes: ["boho", "japandi", "scandi", "coastal", "minimalist"],
    color: "#3a5a3a",
    recommendedClearance: 0.5,
  },
  {
    id: "ottoman",
    name: "Ottoman",
    category: "misc",
    shape: "rect",
    width: 3,
    depth: 2,
    themes: ["mid-century-modern", "boho", "modern-farmhouse", "art-deco"],
    color: "#7a6147",
    recommendedClearance: 1,
  },
];

export function getCatalogItem(id: string): CatalogItem | undefined {
  return CATALOG.find((c) => c.id === id);
}

export const CATEGORIES: { id: CatalogItem["category"]; label: string }[] = [
  { id: "seating", label: "Seating" },
  { id: "tables", label: "Tables" },
  { id: "beds", label: "Beds" },
  { id: "storage", label: "Storage" },
  { id: "rugs", label: "Rugs" },
  { id: "lighting", label: "Lighting" },
  { id: "misc", label: "Misc" },
];
